<template>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
  <p>我的Switch内容</p>
</template>

<script lang='ts'>
export default {
  name: 'SwitchDemo',
};
</script>

<style scoped>

</style>
